package ru.redbyte.arch.plugin.utils

const val INTERNAL = "internal"
const val CLASS = "class"
const val DATA_CLASS = "data class"
const val SEALED_CLASS = "sealed class"
const val PRIVATE = "private"
const val FUN = "fun"
const val OVERRIDE = "override"
const val IMPORT = "import"
const val PACKAGE = "package"
const val OBJECT = "object"
const val COMPANION_OBJECT = "companion object"
const val ANDROIDX_COMPOSE = "androidx.compose"
const val ANDROIDX = "androidx"
const val COMPOSABLE = "Composable"
const val TAB = "    "
const val DAGGER = "dagger"
const val HILT = "hilt"
const val MODULE = "Module"
const val PROVIDES = "Provides"
const val VIEW_MODEL_COMPONENT = "ViewModelComponent"
const val IMPLEMENTATION = "implementation"
const val PROJECT = "project"
const val PROJECT_THEMED_PREVIEW = "ru.otpbank.mobile.utils.ThemedPreview"
const val PROJECT_THEME = "ru.otpbank.mobile.theme.OtpTheme"
const val PROJECT_BASE_VIEW_MODEL = "ru.otpbank.mobile.presentation.base.compose.BaseViewModel"
const val PROJECT_BASE_TEST = "ru.otpbank.mobile.BaseTest"

